process.env.TZ='Europe/Rome';
const fs=require('fs'),path=require('path'),https=require('https'),http=require('http');
const BASES=['https://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno','http://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno'];
const DATA_DIR=path.join(__dirname,'data'),STATIONS_CACHE=path.join(DATA_DIR,'piemonte-stations-v6.json'),LIVE_CACHE=path.join(DATA_DIR,'piemonte-live-v6.json');
const PIEMONTE_REGION=3,DISPLAY_WINDOW_MIN=5,SCAN_MS=60*1000,STATION_CONCURRENCY=18,DETAIL_CONCURRENCY=20,CACHE_TTL=7*24*60*60*1000;
let stations=[],stationMap=new Map(),live=new Map(),scanPromise=null,lastScan=0,lastUpdated=null,lastError=null,identityCache=new Map();
function now(){return Date.now()} function midnight(){const d=new Date();d.setHours(0,0,0,0);return d.getTime()} function vtDate(){return new Date().toString()}
function request(url,timeout=15000,redirects=0){return new Promise((resolve,reject)=>{if(redirects>4)return reject(new Error('redirect loop'));const u=new URL(url),client=u.protocol==='https:'?https:http;const req=client.get(u,{headers:{'User-Agent':'TrainRadar24-Piemonte/4.0','Accept':'application/json,text/plain,*/*','Connection':'close'}},res=>{if([301,302,303,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return resolve(request(new URL(res.headers.location,u).toString(),timeout,redirects+1))}let body='';res.setEncoding('utf8');res.on('data',c=>body+=c);res.on('end',()=>{if(res.statusCode===204)return resolve('');if(res.statusCode<200||res.statusCode>=300)return reject(new Error(`HTTP ${res.statusCode}`));resolve(body)})});req.setTimeout(timeout,()=>req.destroy(new Error(`timeout ${timeout}ms`)));req.on('error',reject)})}
async function json(p){let last=null;for(const base of BASES){try{const b=await request(base+p);if(!b)return null;return JSON.parse(b)}catch(e){last=e}}throw last||new Error('ViaggiaTreno non raggiungibile')}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){for(;;){const i=next++;if(i>=items.length)return;try{out[i]=await fn(items[i],i)}catch(e){out[i]={error:e.message}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
function save(file,data){try{fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(file,JSON.stringify(data))}catch(e){console.error('cache:',e.message)}}
function loadFile(file){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return null}}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function coordFrom(o,keys){for(const k of keys){const n=num(o?.[k]);if(n!==null)return n}return null}
function stationName(s){return s?.localita?.nomeLungo||s?.nomeLungo||s?.localita?.nomeBreve||s?.nomeBreve||s?.nomeCitta||s?.codiceStazione||s?.codStazione||s?.id||''}
function toStation(raw){const code=raw?.codiceStazione||raw?.codStazione||raw?.id||raw?.localita?.id;if(!code)return null;const lat=coordFrom(raw,['lat','latitudine','latitude','latitudineStazione','y'])??coordFrom(raw?.localita,['lat','latitudine','latitude']);const lon=coordFrom(raw,['lon','lng','longitudine','longitude','longitudineStazione','x'])??coordFrom(raw?.localita,['lon','lng','longitudine','longitude']);return{code,name:stationName(raw),lat,lon,type:Number(raw?.tipoStazione??3),region:Number(raw?.codReg??PIEMONTE_REGION)}}
async function coordinate(code){try{const d=await json(`/getCoordinateStazione/${encodeURIComponent(code)}`);const lat=coordFrom(d,['lat','latitudine','latitude','y']),lon=coordFrom(d,['lon','lng','longitudine','longitude','x']);if(lat!==null&&lon!==null)return{lat,lon}}catch{}return null}
async function loadStations(){const cached=loadFile(STATIONS_CACHE);if(cached?.saved&&Array.isArray(cached.stations)&&now()-cached.saved<CACHE_TTL){stations=cached.stations;stationMap=new Map(stations.map(s=>[s.code,s]));return}const raw=await json(`/elencoStazioni/${PIEMONTE_REGION}`);if(!Array.isArray(raw)||!raw.length)throw new Error('elencoStazioni/3 vuoto');const base=raw.map(toStation).filter(Boolean).filter(s=>s.type!==4);const enriched=await mapLimit(base,STATION_CONCURRENCY,async s=>{if(s.lat!==null&&s.lon!==null)return s;const c=await coordinate(s.code);return c?{...s,...c}:null});stations=enriched.filter(x=>x&&Number.isFinite(x.lat)&&Number.isFinite(x.lon));stationMap=new Map(stations.map(s=>[s.code,s]));if(stations.length<20)throw new Error(`Coordinate stazioni Piemonte insufficienti: ${stations.length}`);save(STATIONS_CACHE,{saved:now(),stations})}
function trainNumber(raw){return String(raw?.numeroTreno??raw?.compNumeroTreno??raw?.train_number??'').trim().replace(/\D/g,'')}
function category(raw){const s=`${raw?.categoria||''} ${raw?.categoriaDescrizione||''} ${raw?.compTipologiaTreno||''} ${raw?.compNumeroTreno||''}`.toUpperCase();const c=Number(raw?.codiceCliente);if(c===1||/\b(FR|FA|FB|AV)\b|FRECCIA/.test(s))return'AV';if(c===4||/\bICN?\b|INTERCITY/.test(s))return'IC';if(/\bRV\b|REGIONALE VELOCE/.test(s))return'RV';if(/MALPENSA|\bMXP\b/.test(s))return'MXP';if(/SFM/.test(s))return'SFM';return'REG'}
function timeMs(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);if(Number.isFinite(n)&&n>1000000000)return n;const d=Date.parse(String(v));if(Number.isFinite(d))return d;const m=String(v).match(/(\d{1,2}):(\d{2})/);if(m){const x=new Date();x.setHours(Number(m[1]),Number(m[2]),0,0);return x.getTime()}return null}
function delay(v){if(typeof v==='number'&&Number.isFinite(v))return Math.round(v);const s=String(v??'').replace(/&nbsp;/g,' ').trim();if(!s||/in\s*orario|puntuale|on\s*time/i.test(s))return 0;const m=s.match(/(-?\d+(?:[.,]\d+)?)\s*(?:min|minute)/i);return m?Math.round(Number(m[1].replace(',','.'))):0}
function stopTime(s){return timeMs(s?.programmata??s?.partenzaTeorica??s?.arrivoTeorico??s?.partenza_teorica??s?.arrivo_teorico)}
function normalizeStops(rawStops){return(Array.isArray(rawStops)?rawStops:[]).map((s,i)=>{const id=s?.id||s?.codiceStazione||s?.codStazione||'';const meta=stationMap.get(id);return{id,name:s?.stazione||s?.nomeStazione||meta?.name||id,lat:meta?.lat??null,lon:meta?.lon??null,scheduled:stopTime(s),arr:timeMs(s?.arrivoTeorico||s?.arrivo_teorico),dep:timeMs(s?.partenzaTeorica||s?.partenza_teorica),actual:timeMs(s?.effettiva||s?.effettivaZero),arrReal:timeMs(s?.arrivoReale),depReal:timeMs(s?.partenzaReale),delay:delay(s?.ritardo),delayArr:delay(s?.ritardoArrivo),delayDep:delay(s?.ritardoPartenza),actualFermataType:Number.isFinite(Number(s?.actualFermataType))?Number(s.actualFermataType):null,region:meta?.region??null,seq:i}}).filter(s=>s.id&&s.scheduled)}
function stopRealtime(stops){let last=null,bestDelay=null;for(const s of stops){const actuals=[s.actual,s.arrReal,s.depReal].filter(Number.isFinite);if(actuals.length){const actual=Math.max(...actuals);if(!last||actual>last.actual)last={station:s.name,actual}}const vals=[s.delayArr,s.delayDep,s.delay].filter(Number.isFinite);if(vals.length&&actuals.length)bestDelay={value:vals[vals.length-1],actual:Math.max(...actuals)}}return{last,bestDelay}}
function position(stops,globalDelay,nowMs){if(stops.length<1)return null;const ss=stops.map(s=>({...s,effective:s.scheduled+Math.max(0,globalDelay||0)*60000})),first=ss[0],last=ss.at(-1);if(nowMs<first.effective-DISPLAY_WINDOW_MIN*60000)return null;if(nowMs>last.effective+DISPLAY_WINDOW_MIN*60000)return null;if(nowMs>=last.effective)return{status:'arrived',lat:last.lat,lon:last.lon,nextStop:null,segment:ss.length-1,progress:100};for(let i=0;i<ss.length-1;i++){const a=ss[i],b=ss[i+1];if(nowMs>=a.effective&&nowMs<=b.effective){const q=Math.max(0,Math.min(1,(nowMs-a.effective)/Math.max(1,b.effective-a.effective)));const lat=Number.isFinite(a.lat)&&Number.isFinite(b.lat)?a.lat+(b.lat-a.lat)*q:(Number.isFinite(a.lat)?a.lat:(Number.isFinite(b.lat)?b.lat:null));const lon=Number.isFinite(a.lon)&&Number.isFinite(b.lon)?a.lon+(b.lon-a.lon)*q:(Number.isFinite(a.lon)?a.lon:(Number.isFinite(b.lon)?b.lon:null));return{status:'running',lat,lon,nextStop:b.name,segment:i,progress:Math.round(q*100)}}}if(nowMs<=first.effective)return{status:'not_departed',lat:first.lat,lon:first.lon,nextStop:first.name,segment:-1,progress:0};return null}
function piemontePosition(stops,globalDelay,nowMs){const p=position(stops,globalDelay,nowMs);if(!p)return null;const inPiemonte=s=>stationMap.has(s.id)||s.region===PIEMONTE_REGION;if(p.status==='not_departed')return inPiemonte(stops[0])?p:null;if(p.status==='arrived')return inPiemonte(stops.at(-1))?p:null;const a=stops[p.segment],b=stops[p.segment+1];return a&&b&&inPiemonte(a)&&inPiemonte(b)?p:null}
async function resolveIdentity(raw){const n=trainNumber(raw);if(!n)return null;const day=String(raw?.dataPartenzaTreno||raw?.millisDataPartenza||midnight()),key=`${n}|${day}`;if(identityCache.has(key))return identityCache.get(key);try{const d=await json(`/cercaNumeroTreno/${encodeURIComponent(n)}`);if(d&&d.codLocOrig){const x={originCode:d.codLocOrig,originName:d.descLocOrig||null,day:Number(d.millisDataPartenza||day)};identityCache.set(key,x);return x}}catch{}try{const text=await json(`/cercaNumeroTrenoTrenoAutocomplete/${encodeURIComponent(n)}`);const lines=String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),wanted=lines.find(line=>line.includes(`|${n}-`))||lines[0],m=wanted&&wanted.match(/\|(\d+)-(S\d+)-(\d+)/),name=wanted&&wanted.match(/^\d+\s*-\s*(.*?)\s*\|/);if(m){const x={originCode:m[2],originName:name?name[1].trim():null,day:Number(m[3])};identityCache.set(key,x);return x}}catch{}return null}
function makeTrain(raw,stops,p,n,d,identity){const rt=stopRealtime(stops),globalDelay=Number.isFinite(d)?d:(rt.bestDelay?.value??0),origin=String(raw?.origine||raw?.origineZero||identity?.originName||stops[0]?.name||'').trim(),destination=String(raw?.destinazione||raw?.destinazioneZero||stops.at(-1)?.name||'').trim(),dep=timeMs(raw?.orarioPartenza)||stops[0]?.scheduled,arr=timeMs(raw?.orarioArrivo)||stops.at(-1)?.scheduled,lastStation=String(raw?.stazioneUltimoRilevamento||raw?.stazioneUltimoRilevamentoNome||raw?.ultimaStazioneRilevata||'').trim(),lastTime=timeMs(raw?.oraUltimoRilevamento)||timeMs(raw?.compOraUltimoRilevamento),last=rt.last,lastText=lastStation?(lastTime?`${lastStation} · ${new Date(lastTime).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',hour12:false})}`:lastStation):(last?`${last.station} · ${new Date(last.actual).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',hour12:false})}`:null),status=raw?.nonPartito?'not_departed':raw?.arrivato?'arrived':raw?.circolante?'running':p.status,cat=category(raw);return{trip_id:`vt-${n}-${identity?.originCode||raw?.codOrigine||stops[0]?.id||'x'}-${raw?.dataPartenzaTreno||identity?.day||midnight()}`,source_trip_id:`${n}-${identity?.originCode||raw?.codOrigine||stops[0]?.id||'x'}-${raw?.dataPartenzaTreno||identity?.day||midnight()}`,route:cat,route_name:`${origin} → ${destination}`,category:cat,region:'piemonte',operator:Number(raw?.codiceCliente)===63?'Trenord':'Trenitalia',dep:dep?new Date(dep).toISOString():null,arr:arr?new Date(arr).toISOString():null,origin,destination,train_number:String(n),delay_min:Math.round(globalDelay),delay_known:true,delay_status:globalDelay<5?'on_time':globalDelay<=30?'delayed':'severe_delay',delay_text:Array.isArray(raw?.compRitardoAndamento)?raw.compRitardoAndamento[0]:null,realtime:true,realtime_source:'ViaggiaTreno',realtime_updated_at:new Date().toISOString(),cancelled:['ST','SI','SF'].includes(String(raw?.tipoTreno||''))||Number(raw?.provvedimento)===1,status,nextStop:p.nextStop||null,lat:p.lat,lon:p.lon,realtime_position:true,last_detection_station:lastStation||last?.station||null,last_detection_time:lastTime||last?.actual||null,last_detection_text:lastText,stops,verified_category:cat,verified_train_number:String(n)}}
async function scanStations(){const results=await mapLimit(stations,STATION_CONCURRENCY,async station=>{const [dep,arr]=await Promise.all([json(`/partenze/${encodeURIComponent(station.code)}/${encodeURIComponent(vtDate())}`).catch(()=>[]),json(`/arrivi/${encodeURIComponent(station.code)}/${encodeURIComponent(vtDate())}`).catch(()=>[])]);return[...(Array.isArray(dep)?dep:[]),...(Array.isArray(arr)?arr:[])].map(x=>({...x,_boardStation:station.code,_boardName:station.name}))});const candidates=new Map();for(const batch of results)for(const raw of Array.isArray(batch)?batch:[]){const n=trainNumber(raw);if(!n)continue;const day=String(raw?.dataPartenzaTreno||raw?.millisDataPartenza||midnight());candidates.set(`${n}|${day}`,raw)}return candidates}
async function detail(raw){const n=trainNumber(raw);if(!n)return null;const identity=await resolveIdentity(raw),origin=identity?.originCode||raw?.codOrigine,day=Number(identity?.day||raw?.dataPartenzaTreno||raw?.millisDataPartenza||midnight());if(!origin)return null;try{const d=await json(`/andamentoTreno/${encodeURIComponent(origin)}/${encodeURIComponent(n)}/${day}`);if(d){const stops=normalizeStops(d.fermate);if(stops.length>=2){const baseDelay=delay(d.ritardo),rt=stopRealtime(stops),effective=Number.isFinite(baseDelay)&&baseDelay!==0?baseDelay:(rt.bestDelay?.value??baseDelay);const p=piemontePosition(stops,effective,now());if(!p)return null;return makeTrain({...raw,...d},stops,p,n,effective,identity)}}}catch{}return null}
async function scan(){await loadStations();const candidates=await scanStations(),details=await mapLimit([...candidates.values()],DETAIL_CONCURRENCY,detail),current=now();live=new Map();for(const t of details)if(t){const first=timeMs(t.dep),last=timeMs(t.arr);if(first!==null&&last!==null&&current<=last+DISPLAY_WINDOW_MIN*60000)live.set(t.trip_id,t)}lastScan=current;lastUpdated=new Date().toISOString();lastError=null;save(LIVE_CACHE,{saved:current,trips:[...live.values()]});console.log(`Piemonte realtime: stazioni=${stations.length} candidati=${candidates.size} treni=${live.size}`);return[...live.values()]}
async function realtime(){if(!scanPromise&&(now()-lastScan>=SCAN_MS||!live.size)){scanPromise=scan().catch(e=>{lastError=e.message;console.error('Piemonte realtime:',e.message);const cached=loadFile(LIVE_CACHE);if(cached?.trips)live=new Map(cached.trips.map(t=>[t.trip_id,t]))}).finally(()=>{scanPromise=null})}const current=[...live.values()].filter(t=>{const a=timeMs(t.arr);return a===null||now()<=a+DISPLAY_WINDOW_MIN*60000});return{status:lastError?{error:lastError}:null,trips:current,generatedAt:lastUpdated,source:'ViaggiaTreno realtime Piemonte'}}
module.exports={realtime};
