process.env.TZ='Europe/Rome';
const fs=require('fs'),path=require('path'),AdmZip=require('adm-zip'),https=require('https'),http=require('http');
const ROOT=__dirname,CACHE=path.join(ROOT,'data','national-trips.json');
const STATIC_URL='https://proxy.busone.app/trenitalia/gtfs.zip';
const RT_URL='https://proxy.busone.app/trenitalia/gtfs-rt/trip-updates.json';
function download(url,redirects=0){return new Promise((resolve,reject)=>{if(redirects>6)return reject(new Error('troppi redirect'));const u=new URL(url),client=u.protocol==='http:'?http:https;const req=client.get(u,{headers:{'User-Agent':'TrainRadar24-Nazionale/1.1','Accept':'application/zip,application/json,text/plain,*/*'}},res=>{if([301,302,303,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return resolve(download(new URL(res.headers.location,url).toString(),redirects+1))}if(res.statusCode<200||res.statusCode>=300){res.resume();return reject(new Error(`HTTP ${res.statusCode}`))}const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(Buffer.concat(chunks)))});req.setTimeout(300000,()=>req.destroy(new Error('timeout 300s')));req.on('error',reject)})}
function csv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(quoted){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell.length||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];const head=rows[0].map(x=>x.replace(/^\uFEFF/,'').trim());return rows.slice(1).map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]??''])))}
function file(zip,name){try{const e=zip.getEntry(name);return e?e.getData().toString('utf8'):''}catch{return''}}
function minTime(v){const m=String(v||'').match(/^(\d+):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function today(){const d=new Date();return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function activeServices(calendar,dates){const d=new Date(),day=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][d.getDay()],key=today(),out=new Set();for(const r of calendar)if(String(r.start_date)<=key&&String(r.end_date)>=key&&r[day]==='1')out.add(r.service_id);for(const r of dates)if(String(r.date)===key){if(String(r.exception_type)==='1')out.add(r.service_id);if(String(r.exception_type)==='2')out.delete(r.service_id)}return out}
function classify(route,trip,names){const s=`${trip.train_category||''} ${trip.trip_short_name||''} ${trip.trip_headsign||''} ${route.route_short_name||''} ${route.route_long_name||''}`.toUpperCase();const n=(names||[]).join(' ').toUpperCase();if(/FRECCIAROSSA|FRECCIARGENTO|FRECCIABIANCA|FRECCIA/.test(s)||/\bAV\b/.test(s)||['101'].includes(String(route.route_type)))return'AV';if(/INTERCITY|ICN|INTERCITY NOTTE/.test(s)||/\bIC\b/.test(s)||['102','105'].includes(String(route.route_type)))return'IC';if(/REGIONALE VELOCE|\bRV\b/.test(s)||['103','106'].includes(String(route.route_type))||((/TORINO/.test(s)||/TORINO/.test(n))&&(/MILANO/.test(s)||/MILANO/.test(n))))return'RV';return'REG'}
function normalize(buf){const z=new AdmZip(buf),routes=csv(file(z,'routes.txt')),stops=csv(file(z,'stops.txt')),trips=csv(file(z,'trips.txt')),stopTimes=csv(file(z,'stop_times.txt')),calendar=csv(file(z,'calendar.txt')),dates=csv(file(z,'calendar_dates.txt')),active=activeServices(calendar,dates),stopMap=new Map(stops.map(s=>[s.stop_id,s])),routeMap=new Map(routes.map(r=>[r.route_id,r])),byTrip=new Map(),out=[];for(const s of stopTimes){if(!byTrip.has(s.trip_id))byTrip.set(s.trip_id,[]);byTrip.get(s.trip_id).push(s)}const railTypes=new Set(['2',...Array.from({length:18},(_,i)=>String(100+i))]);for(const t of trips){if(t.service_id&&active.size&&!active.has(t.service_id))continue;const rt=routeMap.get(t.route_id)||{};if(rt.route_type&&!railTypes.has(String(rt.route_type)))continue;const ss=(byTrip.get(t.trip_id)||[]).sort((a,b)=>Number(a.stop_sequence)-Number(b.stop_sequence));if(ss.length<2)continue;const stopsOut=ss.map(s=>{const p=stopMap.get(s.stop_id)||{},arr=minTime(s.arrival_time),dep=minTime(s.departure_time);return{id:s.stop_id,name:p.stop_name||s.stop_id,lat:Number(p.stop_lat),lon:Number(p.stop_lon),arr:s.arrival_time,dep:s.departure_time,arr_min:arr,dep_min:dep}}).filter(s=>Number.isFinite(s.lat)&&Number.isFinite(s.lon)&&s.arr_min!==null&&s.dep_min!==null);if(stopsOut.length<2)continue;const short=String(t.trip_short_name||t.trip_headsign||'').trim();const category=classify(rt,t,stopsOut.map(x=>x.name));out.push({trip_id:`national-${t.trip_id}`,source_trip_id:t.trip_id,route:rt.route_short_name||rt.route_id,route_name:rt.route_long_name||rt.route_short_name||rt.route_id,category,train_number:short||null,region:'nazionale',operator:'Trenitalia',dep:stopsOut[0].dep,arr:stopsOut.at(-1).arr,dep_min:stopsOut[0].dep_min,stops:stopsOut})}return out}
async function load(){try{const buf=await download(STATIC_URL);if(buf.length<10000)throw new Error('GTFS nazionale vuoto');const trips=normalize(buf);if(!trips.length)throw new Error('GTFS nazionale: nessuna corsa ferroviaria valida per oggi');const payload={generatedAt:new Date().toISOString(),source:STATIC_URL,trips};fs.writeFileSync(CACHE,JSON.stringify(payload));console.log(`GTFS nazionale Trenitalia: ${trips.length} corse ferroviarie`);return payload}catch(e){console.error('GTFS nazionale non disponibile:',e.message);if(fs.existsSync(CACHE)){try{const cached=JSON.parse(fs.readFileSync(CACHE,'utf8'));if(Array.isArray(cached.trips)&&cached.trips.length)return cached}catch{}}return{generatedAt:new Date().toISOString(),source:STATIC_URL,trips:[]}}}
async function realtime(){try{const buf=await download(RT_URL);const text=buf.toString('utf8');return JSON.parse(text)}catch(e){console.error('GTFS-RT nazionale non disponibile:',e.message);return null}}
module.exports={load,realtime,CACHE,RT_URL};
