process.env.TZ='Europe/Rome';
const fs=require('fs'),path=require('path'),http=require('http'),https=require('https');
const ROOT=__dirname,DATA_DIR=path.join(ROOT,'data');
const STATIONS_CACHE=path.join(DATA_DIR,'national-stations.json'),LIVE_CACHE=path.join(DATA_DIR,'national-live.json');
const BASES=['http://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno','https://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno'];
const DISPLAY_WINDOW=5,SCAN_MS=5*60*1000,STATION_CONCURRENCY=28,DETAIL_CONCURRENCY=32,STATION_LIMIT=320,CACHE_TTL=24*60*60*1000;
let stations=[],stationMap=new Map(),live=new Map(),lastScan=0,lastUpdated=null,lastError=null,scanPromise=null;
function now(){return Date.now()}
function midnight(){const d=new Date();d.setHours(0,0,0,0);return d.getTime()}
function vtDate(){const d=new Date();const wd=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d.getDay()],mo=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][d.getMonth()];const pad=n=>String(n).padStart(2,'0');const off=-d.getTimezoneOffset(),sgn=off>=0?'+':'-',oh=pad(Math.floor(Math.abs(off)/60)),om=pad(Math.abs(off)%60);return `${wd} ${mo} ${pad(d.getDate())} ${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())} GMT${sgn}${oh}${om}`}
function request(url,timeout=10000,redirects=0){return new Promise((resolve,reject)=>{if(redirects>4)return reject(new Error('redirect loop'));const u=new URL(url),client=u.protocol==='https:'?https:http;const req=client.get(u,{headers:{'User-Agent':'TrainRadar24/11.0','Accept':'application/json,text/plain,*/*','Connection':'close'}},res=>{if([301,302,303,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return resolve(request(new URL(res.headers.location,u).toString(),timeout,redirects+1))}let body='';res.setEncoding('utf8');res.on('data',c=>body+=c);res.on('end',()=>{if(res.statusCode===204)return resolve('');if(res.statusCode<200||res.statusCode>=300)return reject(new Error(`HTTP ${res.statusCode}`));resolve(body)})});req.setTimeout(timeout,()=>req.destroy(new Error(`timeout ${timeout}ms`)));req.on('error',reject)})}
async function json(pathname){let err=null;for(const base of BASES){try{const b=await request(base+pathname);if(!b)return null;return JSON.parse(b)}catch(e){err=e}}throw err||new Error('ViaggiaTreno non raggiungibile')}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){for(;;){const i=next++;if(i>=items.length)return;try{out[i]=await fn(items[i],i)}catch(e){out[i]={error:e.message}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
function save(file,data){try{fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(file,JSON.stringify(data))}catch(e){console.error('cache:',e.message)}}
function loadFile(file){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return null}}
function stationName(s){return s?.localita?.nomeLungo||s?.localita?.nomeBreve||s?.nomeCitta||s?.codiceStazione||s?.codStazione||''}
function toStation(s){const code=s?.codiceStazione||s?.codStazione||s?.localita?.id;if(!code)return null;const lat=Number(s?.lat),lon=Number(s?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;return{code,name:stationName(s),lat,lon,type:Number(s?.tipoStazione??3)}}
async function loadStations(){const cached=loadFile(STATIONS_CACHE);if(cached?.saved&&Array.isArray(cached.stations)&&Array.isArray(cached.coords)&&now()-cached.saved<CACHE_TTL){stations=cached.stations;stationMap=new Map(cached.coords);return}
  const regions=await mapLimit(Array.from({length:23},(_,i)=>i),6,async r=>{try{return await json(`/elencoStazioni/${r}`)}catch{return[]}});
  const by=new Map();for(const arr of regions){for(const raw of Array.isArray(arr)?arr:[]){const s=toStation(raw);if(s)by.set(s.code,s)}}
  if(!by.size)throw new Error('elencoStazioni nazionale vuoto');
  stationMap=new Map(by);const main=Array.isArray(regions[0])?regions[0].map(toStation).filter(Boolean):[];const ordered=[...by.values()].sort((a,b)=>(a.type-b.type)||a.name.localeCompare(b.name));
  stations=[...new Map([...main,...ordered].map(s=>[s.code,s])).values()].filter(s=>s.type!==4).slice(0,STATION_LIMIT);
  save(STATIONS_CACHE,{saved:now(),stations,coords:[...stationMap.entries()]});
}
function trainNumber(raw){return String(raw?.numeroTreno??raw?.train_number??'').trim()}
function category(raw){const s=`${raw?.categoria||''} ${raw?.categoriaDescrizione||''} ${raw?.compNumeroTreno||''} ${raw?.compTipologiaTreno||''}`.toUpperCase();const c=Number(raw?.codiceCliente);if(c===1||/FRECCIA|\bAV\b|\bFR\b|\bFA\b|\bFB\b/.test(s))return'AV';if(c===4||/INTERCITY|\bICN?\b/.test(s))return'IC';if(/REGIONALE VELOCE|\bRV\b/.test(s))return'RV';return'REG'}
function ts(v){const n=Number(v);return Number.isFinite(n)&&n>1000000000?n:null}
function stopTime(s){return ts(s?.programmata)||ts(s?.partenza_teorica)||ts(s?.arrivo_teorico)}
function delay(v){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.round(n)):0}
function normalizeStops(rawStops){return(Array.isArray(rawStops)?rawStops:[]).map((s,i)=>{const meta=stationMap.get(s?.id||s?.codLocOrig);const scheduled=stopTime(s);return{id:s?.id||'',name:s?.stazione||meta?.name||s?.id||'',lat:Number(meta?.lat),lon:Number(meta?.lon),scheduled,arr:ts(s?.arrivo_teorico),dep:ts(s?.partenza_teorica),arrReal:ts(s?.arrivoReale),depReal:ts(s?.partenzaReale),delay:delay(s?.ritardo),delayArr:delay(s?.ritardoArrivo),delayDep:delay(s?.ritardoPartenza),type:s?.tipoFermata||'F',actualType:Number(s?.actualFermataType??1),seq:i}}).filter(s=>s.id&&Number.isFinite(s.lat)&&Number.isFinite(s.lon)&&s.scheduled)}
function position(stops,globalDelay,nowMs){if(stops.length<2)return null;const ss=stops.map(s=>({...s,effective:s.scheduled+Math.max(0,globalDelay)*60000})),first=ss[0],last=ss[ss.length-1];if(nowMs<first.effective-DISPLAY_WINDOW*60000)return{status:'not_departed',lat:first.lat,lon:first.lon,nextStop:first.name,progress:0};if(nowMs>last.effective+DISPLAY_WINDOW*60000)return null;if(nowMs>=last.effective)return{status:'arrived',lat:last.lat,lon:last.lon,nextStop:'—',progress:100};for(let i=0;i<ss.length-1;i++){const a=ss[i],b=ss[i+1];if(nowMs>=a.effective&&nowMs<=b.effective){const q=Math.max(0,Math.min(1,(nowMs-a.effective)/Math.max(1,b.effective-a.effective)));return{status:'running',lat:a.lat+(b.lat-a.lat)*q,lon:a.lon+(b.lon-a.lon)*q,nextStop:b.name,progress:Math.round(q*100)}}}return null}
function keepWindow(t,nowMs){const first=t.stops?.[0]?.scheduled,last=t.stops?.at(-1)?.scheduled;if(!first||!last)return false;const d=first+Math.max(0,t.delay_min||0)*60000,a=last+Math.max(0,t.delay_min||0)*60000;return nowMs>=d-DISPLAY_WINDOW*60000&&nowMs<=a+DISPLAY_WINDOW*60000}
function baseObject(raw,stops,originName,destinationName,number,delayMin,p){const day=Number(raw?.dataPartenzaTreno||raw?.millisDataPartenza||midnight());const origin=raw?.codOrigine||raw?.codLocOrig||stops[0]?.id||'';const id=`national-${number}-${origin}-${day}`;return{trip_id:id,source_trip_id:`${number}-${origin}-${day}`,route:category(raw),route_name:`${originName||stops[0]?.name||'Origine'} → ${destinationName||stops.at(-1)?.name||'Destinazione'}`,category:category(raw),region:'nazionale',operator:'Trenitalia/ViaggiaTreno',dep:new Date(stops[0].scheduled).toISOString(),arr:new Date(stops.at(-1).scheduled).toISOString(),origin:originName||stops[0].name,destination:destinationName||stops.at(-1).name,train_number:number,delay_min:delayMin,delay_known:true,delay_status:delayMin<5?'on_time':delayMin<=30?'delayed':'severe_delay',realtime:true,realtime_source:'ViaggiaTreno',realtime_updated_at:new Date().toISOString(),cancelled:Number(raw?.provvedimento)===1||String(raw?.tipoTreno||'')==='ST',stops,lat:p.lat,lon:p.lon,status:p.status,nextStop:p.nextStop,progress:p.progress,etaMin:0}}
function fallbackBoard(raw){const n=trainNumber(raw),station=stationMap.get(raw?._boardStation);if(!n||!station)return null;const dep=ts(raw?.orarioPartenza),arr=ts(raw?.orarioArrivo);const boardTime=dep||arr;if(!boardTime)return null;const isArrival=!dep&&!!arr;const originMeta=stationMap.get(raw?.codOrigine||raw?.codLocOrig);const destMeta=stationMap.get(raw?.codDestinazione);const originName=raw?.origine||originMeta?.name||'Origine';const destName=raw?.destinazione||destMeta?.name||station.name;let stops;if(isArrival){const firstTime=Math.max(0,arr-60*60000);stops=[{id:originMeta?.code||station.code,name:originName,lat:originMeta?.lat??station.lat,lon:originMeta?.lon??station.lon,scheduled:firstTime},{id:station.code,name:destName,lat:station.lat,lon:station.lon,scheduled:arr}]}else{const lastTime=arr||dep+60*60000;stops=[{id:station.code,name:station.name,lat:station.lat,lon:station.lon,scheduled:dep},{id:destMeta?.code||station.code,name:destName,lat:destMeta?.lat??station.lat,lon:destMeta?.lon??station.lon,scheduled:lastTime}]}const p=position(stops,delay(raw?.ritardo),now());if(!p)return null;return baseObject(raw,stops,originName,destName,n,delay(raw?.ritardo),p)}
async function board(code,kind){const endpoint=kind==='dep'?'partenze':'arrivi';try{return await json(`/${endpoint}/${encodeURIComponent(code)}/${encodeURIComponent(vtDate())}`)}catch{return[]}}
async function discover(){const results=await mapLimit(stations,STATION_CONCURRENCY,async s=>{const [dep,arr]=await Promise.all([board(s.code,'dep'),board(s.code,'arr')]);return[...(Array.isArray(dep)?dep:[]),...(Array.isArray(arr)?arr:[])].map(x=>({...x,_boardStation:s.code,_boardName:s.name}))});const seen=new Map();for(const batch of results){for(const raw of Array.isArray(batch)?batch:[]){const n=trainNumber(raw),origin=raw?.codOrigine||raw?.codLocOrig||'';const day=String(raw?.dataPartenzaTreno||raw?.millisDataPartenza||midnight());if(!n||!origin)continue;const key=`${n}|${origin}|${day}`;if(!seen.has(key))seen.set(key,raw)}}return[...seen.values()]}
async function detail(raw){const n=trainNumber(raw),origin=raw?.codOrigine||raw?.codLocOrig,day=Number(raw?.dataPartenzaTreno||raw?.millisDataPartenza||midnight());if(!n||!origin||!Number.isFinite(day))return fallbackBoard(raw);try{const d=await json(`/andamentoTreno/${encodeURIComponent(origin)}/${encodeURIComponent(n)}/${day}`);const stops=normalizeStops(d?.fermate);if(stops.length<2)return fallbackBoard(raw);const p=position(stops,delay(d?.ritardo),now());if(!p)return null;return baseObject({...raw,...d,codiceCliente:d?.codiceCliente,categoria:d?.categoria,categoriaDescrizione:d?.categoriaDescrizione,compNumeroTreno:d?.compNumeroTreno,compTipologiaTreno:d?.compTipologiaTreno,numeroTreno:d?.numeroTreno||n,tipoTreno:d?.tipoTreno,provvedimento:d?.provvedimento,origine:d?.origine,destinazione:d?.destinazione,dataPartenzaTreno:d?.dataPartenzaTreno||day},stops,d?.origine||raw?.origine||raw?._boardName,d?.destinazione||raw?.destinazione,n,delay(d?.ritardo),p)}catch{return fallbackBoard(raw)}}
async function scan(){await loadStations();const discovered=await discover();const details=await mapLimit(discovered,DETAIL_CONCURRENCY,detail);const next=new Map();for(const t of details)if(t)next.set(t.trip_id,t);live=next;lastScan=now();lastUpdated=new Date().toISOString();lastError=null;save(LIVE_CACHE,{saved:lastScan,trips:[...live.values()]});console.log(`ViaggiaTreno nazionale: ${stations.length} stazioni, ${discovered.length} corse, ${live.size} treni visibili`);return[...live.values()]}
async function load(){if(!scanPromise&&(now()-lastScan>=SCAN_MS||!live.size)){scanPromise=scan().catch(e=>{lastError=e.message;console.error('ViaggiaTreno nazionale:',e.message);const cached=loadFile(LIVE_CACHE);if(cached?.trips)live=new Map(cached.trips.map(t=>[t.trip_id,t]));return[...live.values()]}).finally(()=>{scanPromise=null})}if(scanPromise&&!live.size){const cached=loadFile(LIVE_CACHE);if(cached?.trips)live=new Map(cached.trips.map(t=>[t.trip_id,t]))}const current=[...live.values()].filter(t=>keepWindow(t,now()));return{generatedAt:new Date().toISOString(),source:'ViaggiaTreno realtime nazionale',trips:current,status:{stations:stations.length,liveTrains:current.length,lastScan:lastUpdated,error:lastError,displayWindowMinutes:DISPLAY_WINDOW,scanning:Boolean(scanPromise)}}}
async function realtime(){return load()}
module.exports={load,realtime,CACHE:LIVE_CACHE,RT_URL:BASES[0],DISPLAY_WINDOW};
