process.env.TZ='Europe/Rome';
const fs=require('fs'),path=require('path'),AdmZip=require('adm-zip'),https=require('https'),http=require('http');
const ROOT=__dirname,DATA=path.join(ROOT,'data'),CACHE=path.join(DATA,'regional-v2.json'),SOURCES_FILE=path.join(DATA,'regional_sources.json');
const NATIONAL_SOURCES=[
  'https://www.sardegnamobilita.it/opendata/dati_trenitalia.zip',
  'https://proxy.busone.app/trenitalia/gtfs.zip'
];
function download(url,redirects=0){return new Promise((resolve,reject)=>{if(redirects>7)return reject(new Error('troppi redirect'));const u=new URL(url),client=u.protocol==='http:'?http:https;const req=client.get(u,{headers:{'User-Agent':'TrainRadar24/4.0','Accept':'application/zip,application/octet-stream,*/*','Connection':'close'}},res=>{if([301,302,303,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return resolve(download(new URL(res.headers.location,url).toString(),redirects+1))}if(res.statusCode<200||res.statusCode>=300){res.resume();return reject(new Error(`HTTP ${res.statusCode}`))}const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve(Buffer.concat(chunks)))});req.setTimeout(180000,()=>req.destroy(new Error('timeout download GTFS')));req.on('error',reject)})}
function csv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(quoted){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell.length||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];const head=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]??''])))}
function file(zip,name){try{const e=zip.getEntry(name);return e?e.getData().toString('utf8'):''}catch{return''}}
function minTime(v){const m=String(v||'').match(/^(\d+):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function today(){const d=new Date();return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function activeServices(calendar,dates){const d=new Date(),day=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][d.getDay()],key=today(),out=new Set();for(const r of calendar)if(String(r.start_date)<=key&&String(r.end_date)>=key&&r[day]==='1')out.add(r.service_id);for(const r of dates)if(String(r.date)===key){if(String(r.exception_type)==='1')out.add(r.service_id);if(String(r.exception_type)==='2')out.delete(r.service_id)}return out}
function loadConfig(){return JSON.parse(fs.readFileSync(SOURCES_FILE,'utf8'))}
function inBox(lat,lon,b){return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=b[0]&&lat<=b[2]&&lon>=b[1]&&lon<=b[3]}
function regionForStops(stops,regions){const scores=new Map();for(const s of stops){for(const[code,r]of Object.entries(regions)){if(inBox(s.lat,s.lon,r.bbox))scores.set(code,(scores.get(code)||0)+1)}}let best='NAZ',score=0;for(const[k,n]of scores)if(n>score){best=k;score=n}return best}
function classify(route,trip,stopsOut){const s=`${trip.train_category||''} ${trip.trip_short_name||''} ${trip.trip_headsign||''} ${route.route_short_name||''} ${route.route_long_name||''}`.toUpperCase();if(/FRECCIAROSSA|FRECCIARGENTO|FRECCIABIANCA|\bFR\b|\bFA\b|\bFB\b|\bAV\b/.test(s))return'AV';if(/INTERCITY|\bICN?\b/.test(s))return'IC';if(/REGIONALE VELOCE|\bRV\b/.test(s))return'RV';return'REG'}
function normalize(buf,source,regions){const z=new AdmZip(buf),routes=csv(file(z,'routes.txt')),stops=csv(file(z,'stops.txt')),trips=csv(file(z,'trips.txt')),stopTimes=csv(file(z,'stop_times.txt')),calendar=csv(file(z,'calendar.txt')),dates=csv(file(z,'calendar_dates.txt')),active=activeServices(calendar,dates);const stopMap=new Map(stops.map(s=>[s.stop_id,s])),routeMap=new Map(routes.map(r=>[r.route_id,r])),byTrip=new Map(),out=[];for(const s of stopTimes){if(!byTrip.has(s.trip_id))byTrip.set(s.trip_id,[]);byTrip.get(s.trip_id).push(s)}for(const t of trips){if(active.size&&!active.has(t.service_id))continue;const rt=routeMap.get(t.route_id)||{},ss=(byTrip.get(t.trip_id)||[]).sort((a,b)=>Number(a.stop_sequence)-Number(b.stop_sequence));if(ss.length<2)continue;const stopsOut=ss.map(s=>{const p=stopMap.get(s.stop_id)||{},arr=minTime(s.arrival_time),dep=minTime(s.departure_time);return{id:s.stop_id,name:p.stop_name||s.stop_id,lat:Number(p.stop_lat),lon:Number(p.stop_lon),arr:s.arrival_time,dep:s.departure_time,arr_min:arr,dep_min:dep}}).filter(s=>Number.isFinite(s.lat)&&Number.isFinite(s.lon)&&s.arr_min!==null&&s.dep_min!==null);if(stopsOut.length<2)continue;const region=source.region||regionForStops(stopsOut,regions);if(region==='NAZ')continue;const short=String(t.trip_short_name||t.trip_id||'').trim();out.push({trip_id:`${region}-${source.id}-${t.trip_id}`,route:rt.route_short_name||t.route_id,route_name:rt.route_long_name||rt.route_short_name||t.route_id,category:classify(rt,t,stopsOut),train_number:short,region,operator:source.operator||'Trenitalia',source:source.id,dep:stopsOut[0].dep,arr:stopsOut.at(-1).arr,dep_min:stopsOut[0].dep_min,arr_min:stopsOut.at(-1).arr_min,stops:stopsOut})}return out}
function dedupe(trips){const m=new Map();for(const t of trips){const k=`${t.train_number}|${t.stops[0]?.name}|${t.stops.at(-1)?.name}|${t.dep}`;if(!m.has(k))m.set(k,t)}return[...m.values()]}
async function load(){fs.mkdirSync(DATA,{recursive:true});const cfg=loadConfig(),regions=cfg.regions||{},all=[],status={};
  for(const[code,r]of Object.entries(regions))for(const url of(r.staticUrls||[])){const source={id:`${code}-official`,region:code,operator:r.operator||'Trenitalia'};try{const trips=normalize(await download(url),source,regions);all.push(...trips);status[source.id]={ok:true,trips:trips.length,source:url,region:code,updatedAt:new Date().toISOString()}}catch(e){status[source.id]={ok:false,error:e.message,source:url,region:code};console.error(`GTFS ${source.id}: ${e.message}`)}}
  for(const url of NATIONAL_SOURCES){const source={id:'national-trenitalia',region:null,operator:'Trenitalia'};try{const trips=normalize(await download(url),source,regions);if(trips.length){all.push(...trips);status[source.id]={ok:true,trips:trips.length,source:url,region:'multi-regione',updatedAt:new Date().toISOString()};break}}catch(e){status[source.id]={ok:false,error:e.message,source:url,region:'multi-regione'};console.error(`GTFS nazionale: ${e.message}`)}}
  const trips=dedupe(all),byRegion={};for(const t of trips)(byRegion[t.region]??=[]).push(t);const payload={generatedAt:new Date().toISOString(),regions:Object.fromEntries(Object.entries(regions).map(([k,r])=>[k,{name:r.name,trips:byRegion[k]?.length||0}])),status,trips};if(trips.length){fs.writeFileSync(CACHE,JSON.stringify(payload));return payload}if(fs.existsSync(CACHE))return JSON.parse(fs.readFileSync(CACHE,'utf8'));return payload}
module.exports={load,CACHE};
