process.env.TZ = "Europe/Rome";
const express = require("express");
const cors = require("cors");
const fs = require("fs");
const path = require("path");
const https = require("https");

const app = express();
app.use(cors());
app.use(express.static(path.join(__dirname, "public")));
const PORT = process.env.PORT || 3000;
const TRIPS = JSON.parse(fs.readFileSync(path.join(__dirname, "data", "trips.json"), "utf8"));
const ROUTE_NAMES = {S6:"Novara – Milano Passante – Treviglio",R27:"Novara Nord – Saronno – Milano Cadorna",R25:"Mortara – Novara"};
const STATION_IDS=["S00248","S00023","S00034","S01066"];
function haversine(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b);const x=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function prepareTrip(t){let dist=0,cum=[0];for(let i=1;i<t.stops.length;i++){dist+=haversine(t.stops[i-1].lat,t.stops[i-1].lon,t.stops[i].lat,t.stops[i].lon);cum.push(dist)}return {...t,cumDist:cum,totalDist:dist};}
const PREPARED_TRIPS=TRIPS.map(prepareTrip);
function romeNow(){const d=new Date();return d.getHours()*60+d.getMinutes()+d.getSeconds()/60;}
function romeDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function tripValidToday(t){const m=t.trip_id?.match(/-(\d{4}-\d{2}-\d{2})-(\d{4}-\d{2}-\d{2})$/);if(!m)return true;const d=romeDate();return d>=m[1]&&d<=m[2];}
function estimatePosition(trip,nowMin,delay=0){const first=trip.stops[0],last=trip.stops.at(-1),dep=first.dep_min+delay,arr=last.arr_min+delay;if(nowMin<dep-5||nowMin>arr+5)return null;if(nowMin<=dep)return{status:"not_departed",lat:first.lat,lon:first.lon,nextStop:first.name,etaMin:Math.max(0,Math.round(dep-nowMin))};if(nowMin>=arr)return{status:"arrived",lat:last.lat,lon:last.lon,nextStop:null,etaMin:0};for(let i=0;i<trip.stops.length-1;i++){const a=trip.stops[i],b=trip.stops[i+1],ad=a.dep_min+delay,ba=b.arr_min+delay;if(nowMin>=ad&&nowMin<=ba){const q=(nowMin-ad)/(ba-ad||1);return{status:"running",lat:a.lat+(b.lat-a.lat)*q,lon:a.lon+(b.lon-a.lon)*q,fromStop:a.name,nextStop:b.name,etaMin:Math.max(0,Math.round(ba-nowMin)),progress:Math.round(q*100)}}}return null;}
function scheduledTrainNumber(trip){const raw=String(trip.trip_id||"").split("-")[0];if(trip.route==="S6"&&/^124\d+$/.test(raw))return raw.slice(1);if(trip.route==="R25"&&/^111\d+$/.test(raw))return raw.slice(1);if(trip.route!=="R27")return null;const dep=trip.stops[0]?.dep_min;const origin=trip.stops[0]?.id;const novara={371:"4214",431:"4222",491:"4226",551:"4232",611:"4236",671:"4240",731:"4244",791:"4246",851:"4250",911:"4254",971:"4260",1031:"4266",1091:"4270",1151:"4276",1211:"4280"};const cadorna={407:"4219",467:"4225",527:"4229",587:"4235",647:"4241",707:"4245",767:"4249",827:"4255",887:"4259",947:"4265",1007:"4273",1067:"4279"};if(origin==="S00023")return novara[dep]||null;if(origin==="S01066")return cadorna[dep]||null;return null;}
let realtime={available:false,updatedAt:null,records:[],error:null};
function fetchJson(url){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{"User-Agent":"TrainRadar24-Novara/1.0","Accept":"application/json,text/plain,*/*"}},res=>{let body="";res.setEncoding("utf8");res.on("data",c=>body+=c);res.on("end",()=>{if(res.statusCode===204)return resolve(null);if(res.statusCode<200||res.statusCode>=300)return reject(new Error(`HTTP ${res.statusCode}`));try{resolve(JSON.parse(body))}catch(e){reject(new Error("JSON non valido"))}})});req.setTimeout(9000,()=>req.destroy(new Error("timeout")));req.on("error",reject);});}
function vtDate(){return new Date().toString();}
function minuteFromDate(v){if(v===null||v===undefined)return null;const n=Number(v);if(Number.isFinite(n)){const d=new Date(n);return d.getHours()*60+d.getMinutes()}const m=String(v).match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null;}
function parseDelayValue(v){if(v===null||v===undefined)return null;if(typeof v==='number'&&Number.isFinite(v))return Math.max(0,Math.round(v));const s=String(v).replace(/&nbsp;/g,' ').trim();if(!s)return null;if(/in\s*orario|on\s*time|puntuale/i.test(s))return 0;const m=s.match(/(?:ritardo(?:\s+di)?|delay(?:\s+of)?)?\s*(-?\d+(?:[.,]\d+)?)\s*(?:min|minute)?/i);if(!m)return null;const n=Number(m[1].replace(',','.'));return Number.isFinite(n)?Math.max(0,Math.round(n)):null;}
function delayFromStop(s){if(!s||typeof s!=="object")return null;for(const key of ["ritardo","ritardoPartenza","ritardoArrivo"]){const n=parseDelayValue(s[key]);if(n!==null)return n;}const scheduled=Number(s.programmata??s.partenzaTeorica??s.arrivoTeorico);const actual=Number(s.effettiva??s.partenzaReale??s.arrivoReale);if(Number.isFinite(scheduled)&&Number.isFinite(actual)&&actual>0)return Math.max(0,Math.round((actual-scheduled)/60000));return null;}
function parseVT(item,stationId){const min=minuteFromDate(item?.orarioPartenza);if(min===null)return null;let delay=parseDelayValue(item?.ritardo);if(delay===null)delay=parseDelayValue(item?.compRitardoAndamento?.[0]);if(delay===null)delay=parseDelayValue(item?.compRitardo?.[0]);if(delay===null)delay=0;const number=String(item?.numeroTreno??"").trim();if(!number)return null;return{stationId,number,scheduledMin:min,delayMin:delay,destination:item?.destinazione||null,cancelled:Number(item?.provvedimento)===1,updatedAt:new Date().toISOString(),source:"partenze"};}
function midnightMillis(){const d=new Date();d.setHours(0,0,0,0);return d.getTime();}
function parseAndamento(data,trip,number){if(!data||typeof data!=="object")return null;let delay=null;for(const key of ["ritardo","ritardoPartenza","ritardoArrivo"]){const n=parseDelayValue(data[key]);if(n!==null){delay=n;break;}}if(delay===null){for(const key of ["compRitardoAndamento","compRitardo"]){const n=parseDelayValue(Array.isArray(data[key])?data[key][0]:data[key]);if(n!==null){delay=n;break;}}}const stops=Array.isArray(data.fermate)?data.fermate:[];let latest=null;for(const s of stops){const d=delayFromStop(s);if(d!==null)latest=d;}if(latest!==null)delay=latest;if(delay===null)return null;return{stationId:trip.stops[0].id,number:String(number),scheduledMin:trip.stops[0].dep_min,delayMin:delay,cancelled:["ST","SI","SF"].includes(String(data.tipoTreno||"")),updatedAt:new Date().toISOString(),source:"andamentoTreno"};}
function parseTratteCanvas(data,trip,number){if(!Array.isArray(data)||!data.length)return null;let delay=null;let lastRelevant=null;for(const entry of data){const s=entry?.fermata||entry;if(!s)continue;const d=delayFromStop(s);if(d!==null){delay=d;lastRelevant=s;}if(entry?.stazioneCorrente===true||entry?.stazioneCorrente===1)lastRelevant=s;}if(delay===null)return null;return{stationId:trip.stops[0].id,number:String(number),scheduledMin:trip.stops[0].dep_min,delayMin:delay,cancelled:false,updatedAt:new Date().toISOString(),source:"tratteCanvas"};}
async function resolveTrainKey(number,originId){try{const raw=await new Promise((resolve,reject)=>{const url=`https://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno/cercaNumeroTrenoTrenoAutocomplete/${encodeURIComponent(number)}`;https.get(url,{headers:{"User-Agent":"TrainRadar24-Novara/1.0","Accept":"text/plain,*/*"}},res=>{let b="";res.setEncoding("utf8");res.on("data",c=>b+=c);res.on("end",()=>resolve(b))}).on("error",reject)});const today=romeDate().split("-").reverse().map(x=>x.slice(-2)).join("/");const lines=String(raw).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);for(const line of lines){const parts=line.split("|");if(parts.length<2)continue;const right=parts[1].split("-");if(right[0]===String(number)&&right[1]===originId&&line.includes(today))return Number(right[2]);}const same=lines.find(line=>line.split("|")[1]?.split("-")[1]===originId);if(same){const ts=same.split("|")[1].split("-")[2];if(ts)return Number(ts);}return null}catch(e){return null;}}
async function refreshRealtime(){const records=[];let errors=[];const date=encodeURIComponent(vtDate());for(const stationId of STATION_IDS){try{const data=await fetchJson(`https://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno/partenze/${stationId}/${date}`);if(Array.isArray(data))for(const item of data){const x=parseVT(item,stationId);if(x)records.push(x)}}catch(e){errors.push(`${stationId}: ${e.message}`)}}const now=romeNow();const active=PREPARED_TRIPS.filter(t=>tripValidToday(t)&&now>=t.stops[0].dep_min-5&&now<=t.stops.at(-1).arr_min+5);for(const trip of active){const number=scheduledTrainNumber(trip);if(!number)continue;try{const exactMillis=await resolveTrainKey(number,trip.stops[0].id);const dayMillis=Number.isFinite(exactMillis)?exactMillis:midnightMillis();const base=`https://www.viaggiatreno.it/infomobilita/resteasy/viaggiatreno`;let data=await fetchJson(`${base}/andamentoTreno/${trip.stops[0].id}/${number}/${dayMillis}`);let x=parseAndamento(data,trip,number);if(!x){const canvas=await fetchJson(`${base}/tratteCanvas/${trip.stops[0].id}/${number}/${dayMillis}`);x=parseTratteCanvas(canvas,trip,number)}if(x)records.push(x);else errors.push(`${number}: nessun dato andamento`) }catch(e){errors.push(`${number}: ${e.message}`)}}if(records.length){realtime={available:true,updatedAt:new Date().toISOString(),records,error:errors.length?errors.join(" | "):null};console.log(`ViaggiaTreno OK: ${records.length} realtime records`)}else{realtime={...realtime,available:false,error:errors.join(" | ")||"Nessun dato realtime"};console.log(`ViaggiaTreno NON DISPONIBILE: ${realtime.error}`)}}
function findRealtime(trip,scheduledNumber){const candidates=realtime.records;if(scheduledNumber){const exact=candidates.find(r=>r.number===scheduledNumber&&r.stationId===trip.stops[0]?.id);if(exact)return exact;const anywhere=candidates.find(r=>r.number===scheduledNumber);if(anywhere)return anywhere;}let best=null;for(const r of candidates){if(r.stationId!==trip.stops[0]?.id)continue;const diff=Math.abs(r.scheduledMin-trip.stops[0].dep_min);if(diff<=3&&(!best||diff<best.diff))best={...r,diff};}return best;}
app.get("/api/trains",(req,res)=>{try{const now=romeNow(),trains=[];for(const trip of PREPARED_TRIPS){if(!tripValidToday(trip))continue;const scheduledNumber=scheduledTrainNumber(trip),live=findRealtime(trip,scheduledNumber),delay=live?live.delayMin:0,pos=estimatePosition(trip,now,delay);if(!pos)continue;const displayNumber=scheduledNumber||live?.number||"";trains.push({trip_id:trip.trip_id,route:trip.route,route_name:ROUTE_NAMES[trip.route]||trip.route,dep:trip.dep,arr:trip.arr,origin:trip.stops[0].name,destination:trip.stops.at(-1).name,train_number:displayNumber,delay_min:delay,delay_known:Boolean(live),delay_status:!live?"unknown":delay<5?"on_time":delay<=30?"delayed":"severe_delay",realtime:Boolean(live),realtime_train_number:displayNumber,realtime_source_number:live?.number||null,realtime_source:live?.source||null,realtime_updated_at:realtime.updatedAt,cancelled:live?.cancelled||false,...pos});}res.json({generated_at:new Date().toISOString(),reference_minutes:Math.round(now),source:realtime.available?"GTFS + ViaggiaTreno realtime":"GTFS static",realtime_available:realtime.available,realtime_updated_at:realtime.updatedAt,count:trains.length,trains});}catch(e){console.error("/api/trains",e);res.status(500).json({error:e.message,trains:[]})}});
app.get("/api/realtime-status",(req,res)=>res.json({available:realtime.available,updated_at:realtime.updatedAt,record_count:realtime.records.length,error:realtime.error}));
app.get("/api/health",(req,res)=>res.json({ok:true,trips:PREPARED_TRIPS.length,date:romeDate(),time:romeNow(),realtime:realtime.available}));
app.get("/api/routes",(req,res)=>res.json(Object.entries(ROUTE_NAMES).map(([id,name])=>({id,name}))));
app.listen(PORT,()=>{console.log(`TrainRadar24 backend attivo su porta ${PORT}`);console.log(`Corse caricate: ${PREPARED_TRIPS.length}`);refreshRealtime().catch(e=>console.error(e));setInterval(()=>refreshRealtime().catch(e=>console.error(e)),30000);});
