process.env.TZ='Europe/Rome';
const express=require('express'),cors=require('cors'),fs=require('fs'),path=require('path');
const national=require('./national-loader'),special=require('./special-realtime');
const app=express();app.use(cors());app.use(express.static(path.join(__dirname,'public')));const PORT=process.env.PORT||3000;
const TRIPS=JSON.parse(fs.readFileSync(path.join(__dirname,'data','trips.json'),'utf8'));
const ROUTE_NAMES={S6:'Novara – Milano Passante – Treviglio',R27:'Novara Nord – Saronno – Milano Cadorna',R25:'Mortara – Novara'};
const MAX_VISIBLE=1000,DISPLAY_WINDOW_MIN=5,PIEMONTE_STATIC_STATIONS=new Set(['S00248','S00252','S00023','S01748','S01749','S00031','S00030','S00032']);
const OUTSIDE_REGION_ROUTES=new Set(['S6','R25','R27']);
function romeNow(){const d=new Date();return d.getHours()*60+d.getMinutes()+d.getSeconds()/60}
function romeDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function haversine(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),x=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function prepareTrip(t){let dist=0,cum=[0];for(let i=1;i<t.stops.length;i++){dist+=haversine(t.stops[i-1].lat,t.stops[i-1].lon,t.stops[i].lat,t.stops[i].lon);cum.push(dist)}return{...t,cumDist:cum,totalDist:dist}}
const PREPARED_TRIPS=TRIPS.map(prepareTrip);
function tripValidToday(t){if(t.region)return true;const m=t.trip_id?.match(/-(\d{4}-\d{2}-\d{2})-(\d{4}-\d{2}-\d{2})$/);if(!m)return true;const d=romeDate();return d>=m[1]&&d<=m[2]}
function category(trip){const x=`${trip.category||''} ${trip.route_name||''} ${trip.route||''}`.toUpperCase();const n=Number(trip.train_number||trip.verified_train_number||'');const routeText=`${trip.origin||''} ${trip.destination||''} ${trip.route_name||''}`.toUpperCase();if(trip.route==='S6'||trip.route==='R25'||trip.route==='R27')return'REG';if(x.includes('FRECCIA')||/\bAV\b/.test(x))return'AV';if(x.includes('INTERCITY')||/\bIC\b/.test(x))return'IC';if(Number.isInteger(n)&&n>=2000&&n<2100&&/MILANO/.test(routeText)&&/TORINO/.test(routeText))return'RV';if(x.includes('REGIONALE VELOCE')||/\bRV\b/.test(x))return'RV';if(x.includes('MALPENSA')||x.includes('MXP'))return'MXP';if(x.includes('SFM'))return'SFM';return'REG'}
function staticTrainNumber(t){if(t.train_number)return String(t.train_number);const id=String(t.trip_id||'').split('-')[0];if(!/^\d+$/.test(id))return'';if(t.route==='S6'&&id.startsWith('1')&&id.length>1)return id.slice(1);if(t.route==='R25'&&id.startsWith('1')&&id.length>1)return id.slice(1);if(t.route==='R27'&&id.startsWith('1904')&&id.length>4)return id.slice(3);return''}
function timeMinutes(v){if(v==null)return null;const m=String(v).match(/(\d{1,2}):(\d{2})/);if(m)return Number(m[1])*60+Number(m[2]);const d=new Date(v);return Number.isFinite(d.getTime())?d.getHours()*60+d.getMinutes()+d.getSeconds()/60:null}
function normalizeMinute(m,now){while(m-now>720)m-=1440;while(now-m>720)m+=1440;return m}
function estimateStatic(trip,now){const first=trip.stops[0],last=trip.stops.at(-1),dep=Number(first.dep_min),arr=Number(last.arr_min);if(!Number.isFinite(dep)||!Number.isFinite(arr))return null;const n=normalizeMinute(now,now),d=normalizeMinute(dep,now),a=normalizeMinute(arr,now);if(n<d-DISPLAY_WINDOW_MIN||n>a+DISPLAY_WINDOW_MIN)return null;if(n<=d)return{status:'not_departed',lat:first.lat,lon:first.lon,nextStop:first.name,segment:-1};if(n>=a)return{status:'arrived',lat:last.lat,lon:last.lon,nextStop:null,segment:trip.stops.length-1};for(let i=0;i<trip.stops.length-1;i++){const s=trip.stops[i],b=trip.stops[i+1],sd=normalizeMinute(Number(s.dep_min),now),ba=normalizeMinute(Number(b.arr_min),now);if(n>=sd&&n<=ba){const q=(n-sd)/Math.max(1,ba-sd);return{status:'running',lat:s.lat+(b.lat-s.lat)*q,lon:s.lon+(b.lon-s.lon)*q,nextStop:b.name,segment:i}}}return null}
function isPiemonteStaticPosition(trip,p){if(!p)return false;if(OUTSIDE_REGION_ROUTES.has(trip.route))return true;const inside=s=>PIEMONTE_STATIC_STATIONS.has(s.id);if(p.status==='not_departed')return inside(trip.stops[0]);if(p.status==='arrived')return inside(trip.stops.at(-1));const a=trip.stops[p.segment],b=trip.stops[p.segment+1];return Boolean(a&&b&&inside(a)&&inside(b))}
function staticTrains(now){const out=[];for(const t of PREPARED_TRIPS){if(!tripValidToday(t))continue;const p=estimateStatic(t,now);if(!p||!isPiemonteStaticPosition(t,p))continue;const cat=category(t),tn=staticTrainNumber(t);out.push({trip_id:t.trip_id,route:t.route,route_code:t.route,route_name:t.route_name||ROUTE_NAMES[t.route]||t.route,category:cat,region:t.region||'regionale',operator:t.operator||'Trenitalia/Trenord',dep:t.dep,arr:t.arr,origin:t.stops[0].name,destination:t.stops.at(-1).name,train_number:tn,verified_train_number:tn,display_train_label:tn,delay_min:0,delay_known:false,delay_status:'unknown',realtime:false,realtime_source:null,realtime_updated_at:null,cancelled:false,stops:t.stops,...p})}return out}
function normName(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function minuteDistance(a,b){const x=timeMinutes(a),y=timeMinutes(b);if(x==null||y==null)return 999;let d=Math.abs(x-y);if(d>720)d=1440-d;return d}
function mergeSpecialRealtime(staticItems,liveItems){return staticItems.map(s=>{if(!OUTSIDE_REGION_ROUTES.has(s.route))return s;const sn=String(s.train_number||'').trim();const byNumber=sn?liveItems.filter(l=>String(l.train_number||l.verified_train_number||'').trim()===sn):[];const pool=byNumber.length?byNumber:liveItems.filter(l=>normName(l.origin)===normName(s.origin)&&normName(l.destination)===normName(s.destination));const match=pool.sort((a,b)=>minuteDistance(a.dep,s.dep)-minuteDistance(b.dep,s.dep))[0];if(!match||(!byNumber.length&&minuteDistance(match.dep,s.dep)>8))return s;const tn=String(match.train_number||match.verified_train_number||s.train_number||'').trim();return{...s,...match,trip_id:s.trip_id,route:s.route,route_code:s.route,route_name:s.route_name,category:'REG',verified_category:'REG',origin:match.origin||s.origin,destination:match.destination||s.destination,train_number:tn,verified_train_number:tn,display_train_label:tn,stops:s.stops,realtime:true,realtime_source:'ViaggiaTreno',delay_known:true,delay_min:Number.isFinite(Number(match.delay_min))?Number(match.delay_min):0,last_detection_station:match.last_detection_station||null,last_detection_time:match.last_detection_time||null,last_detection_text:match.last_detection_text||null}})}
function dedupeTrains(items){const best=new Map();for(const t of items){const n=String(t.train_number||t.verified_train_number||'').trim();const key=n?`${n}|${String(t.origin||'')}|${String(t.destination||'')}`:t.trip_id;const old=best.get(key);if(!old||(!old.realtime&&t.realtime)||(old.delay_known===false&&t.delay_known===true))best.set(key,t)}return[...best.values()]}
app.get('/api/trains',async(req,res)=>{try{const now=romeNow(),staticItems=staticTrains(now);const [live,specialLive]=await Promise.all([national.realtime(),special.realtime()]);const liveItems=[...(Array.isArray(live?.trips)?live.trips:[]),...(Array.isArray(specialLive?.trips)?specialLive.trips:[])];const enrichedStatic=mergeSpecialRealtime(staticItems,liveItems),unique=dedupeTrains([...liveItems,...enrichedStatic]);unique.sort((a,b)=>{const rank=c=>c==='AV'?0:c==='IC'?1:c==='RV'?2:c==='SFM'?3:4,ra=rank(a.category),rb=rank(b.category);if(ra!==rb)return ra-rb;if(a.status==='running'&&b.status!=='running')return-1;if(b.status==='running'&&a.status!=='running')return 1;return(Number(b.delay_min)||0)-(Number(a.delay_min)||0)});const requested=Math.min(MAX_VISIBLE,Math.max(20,Number(req.query.limit)||MAX_VISIBLE));const trains=unique.slice(0,requested);res.json({generated_at:new Date().toISOString(),reference_minutes:Math.round(now),source:'ViaggiaTreno realtime Piemonte + S6/R25/R27',realtime_available:liveItems.length>0,count:trains.length,total_candidates:unique.length,national_status:live?.status||null,trains})}catch(e){console.error('/api/trains',e);res.status(500).json({error:e.message,trains:[]})}});
app.get('/api/piemonte-status',async(req,res)=>{try{const x=await national.realtime();res.json({available:Array.isArray(x?.trips)&&x.trips.length>0,status:x?.status||null})}catch(e){res.status(500).json({available:false,error:e.message})}});
app.get('/api/national-status',async(req,res)=>{try{const x=await national.realtime();res.json({available:Array.isArray(x?.trips)&&x?.trips?.length>0,status:x?.status||null,source:x?.source||'ViaggiaTreno'})}catch(e){res.status(500).json({available:false,error:e.message})}});
app.get('/api/realtime-status',async(req,res)=>{try{const x=await national.realtime();res.json({available:Array.isArray(x?.trips)&&x?.trips?.length>0,updated_at:x?.generatedAt||null,record_count:x?.trips?.length||0,error:x?.status?.error||null})}catch(e){res.status(500).json({available:false,error:e.message})}});
app.get('/api/health',async(req,res)=>{let live=null;try{live=await national.realtime()}catch{}res.json({ok:true,trips:PREPARED_TRIPS.length,date:romeDate(),time:romeNow(),realtime:Boolean(live?.trips?.length)})});
app.get('/api/routes',(req,res)=>res.json(Object.entries(ROUTE_NAMES).map(([id,name])=>({id,name}))));
app.listen(PORT,()=>{console.log(`TrainRadar24 backend Piemonte attivo su porta ${PORT}`);console.log(`Corse statiche caricate: ${PREPARED_TRIPS.length}`);national.realtime().catch(e=>console.error('Avvio ViaggiaTreno:',e.message));special.realtime().catch(e=>console.error('Avvio ViaggiaTreno special:',e.message))});
